Edit homepage
VTUL/vtechworks pull request #656
Opened 2019-11-19 21:05 UTC by kdweeks

I believe I have updated the homepage to Philip's requirements and pushed everything correctly back to the 'edit_homepage' branch.   Please check these changes out for a merge to 'vt_6_x_dev'

I wasn't sure if I should add Reviewers or Assignees so I added @alawvt and @keithgee to both. 

This pull request resolves issue #652.

2019-11-20 19:56 UTC, keithgee commented
@kdweeks I'll take a look at this now, but it occurs to me that Philip should at least have a screenshot or something to verify the changes, because he's the one that specified them.

2019-11-20 21:10 UTC, keithgee requested changes
Kimberli - this file looks good, except for a possible typo with the capitalization of ELEments.

Would you be able to fix it, and then if everything else looks okay we can merge the branch? When I do the merge I might use the option that says to squash the commits - I noticed some of the commits in this pull request are test commits.

Thanks!

2019-11-20 21:10 UTC, keithgee commented on dspace/config/news-xmlui.xml
> +<p>Faculty can deposit items to VTechWorks from ELEments (EFARs). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more
@kdweeks - the capitalization of ELEments here might be a

2019-11-20 21:10 UTC, keithgee commented on dspace/config/news-xmlui.xml
> +<p>Faculty can deposit items to VTechWorks from ELEments (EFARs). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more
Sorry..ELEments might be a typo.

2019-11-20 23:06 UTC, kdweeks commented
Oops yes, I'll fix that and send attach a screenshot.  Thanks so much!

Kimberli Weeks
kdweeks@vt.edu
w. (540) 231-2674 c. 540-835-9136
Technical Director,
Scholarly Communications
University Libraries, Virginia Tech
http://scholar.lib.vt.edu


On Wed, Nov 20, 2019 at 4:10 PM keithgee <notifications@github.com> wrote:

> *@keithgee* requested changes on this pull request.
>
> Kimberli - this file looks good, except for a possible typo with the
> capitalization of ELEments.
>
> Would you be able to fix it, and then if everything else looks okay we can
> merge the branch? When I do the merge I might use the option that says to
> squash the commits - I noticed some of the commits in this pull request are
> test commits.
>
> Thanks!
> ------------------------------
>
> In dspace/config/news-xmlui.xml
> <https://github.com/VTUL/vtechworks/pull/656#discussion_r348744633>:
>
> >
>  <p>Want to publish a standalone dataset? Visit <xref target="https://data.lib.vt.edu/" rend="a-bold">VTechData</xref>.</p>
>
> -<p>Faculty can deposit items to VTechWorks from the Electronic Faculty Activity Reporting System (Elements). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more and to log in to Elements.</p>
> +<p>Faculty can deposit items to VTechWorks from ELEments (EFARs). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more and to log in to Elements.</p>
>
> @kdweeks <https://github.com/kdweeks> - the capitalization of ELEments
> here might be a
> ------------------------------
>
> In dspace/config/news-xmlui.xml
> <https://github.com/VTUL/vtechworks/pull/656#discussion_r348744737>:
>
> >
>  <p>Want to publish a standalone dataset? Visit <xref target="https://data.lib.vt.edu/" rend="a-bold">VTechData</xref>.</p>
>
> -<p>Faculty can deposit items to VTechWorks from the Electronic Faculty Activity Reporting System (Elements). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more and to log in to Elements.</p>
> +<p>Faculty can deposit items to VTechWorks from ELEments (EFARs). Visit the Provost's <xref target="http://provost.vt.edu/faculty_affairs/efars.html" rend="a-bold">Elements page</xref> to learn more and to log in to Elements.</p>
>
> Sorry..ELEments might be a typo.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VTUL/vtechworks/pull/656?email_source=notifications&email_token=AADTQ4RBQXS4JBSYZQXCVDTQUWRUDA5CNFSM4JPJMFO2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCMLRBPA#pullrequestreview-320278716>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADTQ4VGZMJF47FAYO7WMXDQUWRUDANCNFSM4JPJMFOQ>
> .
>

2019-11-21 00:07 UTC, kdweeks commented
@keithgee I fixed the typo.  @pyc1 I am attaching a screenshot for your review.
![vtechworks_homepage](https://user-images.githubusercontent.com/473202/69288884-e1548980-0bc8-11ea-945d-90e2ec23f4a9.jpg)

2019-11-21 13:02 UTC, pyc1 commented
Looks good Kimberli, thanks!

2019-11-21 16:26 UTC, kdweeks commented
@pyc1 Thanks!

2019-11-22 00:09 UTC, keithgee approved these changes

2019-11-22 00:10 UTC, merged

2019-11-25 16:39 UTC, alawvt commented
Looks good. @kdweeks, thank you for preparing this pull request and @keithgee and @pyc1 , thank you for reviewing and merging it.